# Generated by Django 2.2.3 on 2019-08-07 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('CA', 'Current Account'), ('SL', 'Salary Account'), ('SA', 'Savings Account'), ('FV', 'Food Voucher'), ('MV', 'Meal Voucher'), ('W', 'Wallet')], max_length=10)),
                ('bank_name', models.CharField(choices=[('SA', 'Santander'), ('CX', 'Caixa'), ('BA', 'Bradesco'), ('NU', 'Nu Bank'), ('MV', 'Meal Valcher'), ('FV', 'Food Valcher')], max_length=10, null=True)),
                ('balance', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('F', 'Food'), ('S', 'Snack'), ('B', 'Bill'), ('C', 'Clothing')], max_length=10)),
                ('price', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
