# Generated by Django 2.2.3 on 2019-08-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190811_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.CharField(max_length=100000000000),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=100000000000),
        ),
    ]
